### ISSUE TITLE
install.sh clears user's entire crontab

### ISSUE THREAD

**Issue by kvz** [philcryer/lipsync#26]

**Comment by philcryer** [comment]
this is fixed, as per this commit:
https://github.com/philcryer/lipsync/blob/ee817c13476bc71b157584e7c72c63a5bc8af918/install.sh#L153

thanks!

**Comment by Thynix** [comment]
This still happens if install.sh is run as root. This is because it sets the target user's crontab to the current user's crontab with the line appended. The target user's contab may disappear or otherwise be modified in unexpected ways if the current user is root.

`(crontab -l; echo "$newcronjob") | crontab -u $username -  #list crontab, read entry from crontab, add line from stdin to crontab`

should therefore be

`(crontab -u $username -l; echo "$newcronjob") | crontab -u $username -  #list crontab, read entry from crontab, add line from stdin to crontab`
